apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1007
        runAsGroup: 0
        fsGroup: 0
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: backend
        image: ghcr.io/cubebleu1/craftedby-backend-containers:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/src/fabriquepar/.env
          name: laravel-env
          subPath: .env
          readOnly: true
      volumes:
      - name: laravel-env
        configMap:
          defaultMode: 420
          name: laravel-env
