apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1007
        runAsGroup: 0
        fsGroup: 0
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: frontend
        image: ghcr.io/cubebleu1/craftedby-frontend-containers:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/src/fabriquepar/.env
          name: vite-env
          subPath: .env
          readOnly: true
      volumes:
      - name: vite-env
        configMap:
          defaultMode: 420
          name: vite-env
