apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
data:
  MYSQL_PASSWORD: {{ .Values.database.password | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.database.password | b64enc }}
  MYSQL_USER: {{ .Values.database.username | b64enc }}
  MYSQL_DATABASE: {{ .Values.database.name | b64enc }}