apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-front
data:
  default.conf : |
    server {
      listen       80;
      listen  [::]:80;

      location / {
          root /usr/share/nginx/html/fabriquepar;
          try_files $uri $uri/ /index.html;
      }

      location /api {
          proxy_pass http://backend/api;
      }

      location /images {
          proxy_pass http://backend/images;
      }
    }