kind: ConfigMap
apiVersion: v1
metadata:
  name: vite-env
data:
  .env: |
    VITE_API_ENDPOINT="http://{{ .Values.url }}/api"
    VITE_IMAGE_BASE_URL="http://{{ .Values.url }}"

    VITE_STRIPE_KEY=pk_test_PZ5P8UpDWL0CqulY6YJjRzGo00vQtn1Ff3
    VITE_STRIPE_SECRET=sk_test_sgFQbF0KnQt7Me5J852syFSJ00GklPEL7C