name: Security IaC
on:
  push:
    branches:
    - "main"
  pull_request:

jobs: 
  KICS:
    environment: Dev
    runs-on: ubuntu-latest
    name: Security checking of helm chart
    steps: 
    - uses: actions/checkout@v3

    - name: run kics Scan
      uses: checkmarx/kics-github-action@v2.1.0
      with:
        path: templates
        token: ${{ secrets.GITHUB_TOKEN }}
        output_path: results-dir
        output_formats: 'sarif'
        ignore_on_exit: results
        enable_comments: true

    - name: Show results
      run: cat results-dir/results.sarif

    - name: Upload results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results-dir/results.sarif

